defmodule ForumApp.Repo.Migrations.FirstMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :contents, :text, null: false
      add :board_id, :uuid
    end

    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :contents, :text, null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "comments_post_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:boards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posts) do
      modify :board_id,
             references(:boards,
               column: :id,
               name: "posts_board_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:boards) do
      add :name, :text, null: false
    end
  end

  def down do
    alter table(:boards) do
      remove :name
    end

    drop constraint(:posts, "posts_board_id_fkey")

    alter table(:posts) do
      modify :board_id, :uuid
    end

    drop table(:boards)

    drop constraint(:comments, "comments_post_id_fkey")

    drop table(:comments)

    drop table(:posts)
  end
end
